FROM golang:1.14.7

WORKDIR /go/src/app
RUN git config --global http.https://gopkg.in.followRedirects true
RUN git clone https://github.com/techievee/ethash-mining-pool.git

WORKDIR /go/src/app/ethhash-mining-pool
RUN git checkout V2.0_Eth_11
RUN make

COPY config_unlocker.json .

CMD ["./build/bin/ethash-mining-pool", "config_unlocker.json"]
